import coursePiano from "@/assets/course-piano.jpg";
import courseGuitar from "@/assets/course-guitar.jpg";
import courseProduction from "@/assets/course-production.jpg";

export const courses = [
  {
    title: "Fundamentos de Piano Clásico",
    instructor: "María González",
    price: "$49.99",
    image: coursePiano,
    category: "Piano",
    duration: "8 semanas",
    rating: 4.9,
  },
  {
    title: "Teoría Musical Completa",
    instructor: "Pedro Sánchez",
    price: "Gratis",
    isFree: true,
    image: coursePiano,
    category: "Teoría Musical",
    duration: "6 semanas",
    rating: 4.7,
  },
  {
    title: "Guitarra para Principiantes",
    instructor: "Carlos Ramírez",
    price: "$39.99",
    image: courseGuitar,
    category: "Guitarra",
    duration: "10 semanas",
    rating: 4.8,
  },
  {
    title: "Producción Musical Moderna",
    instructor: "Ana Torres",
    price: "$59.99",
    image: courseProduction,
    category: "Producción",
    duration: "12 semanas",
    rating: 5.0,
  },
  {
    title: "Técnicas Avanzadas de Piano",
    instructor: "María González",
    price: "$69.99",
    image: coursePiano,
    category: "Piano",
    duration: "10 semanas",
    rating: 4.9,
  },
  {
    title: "Manejo de Secuencias y Monitoreo en Vivo",
    instructor: "Roberto Díaz",
    price: "$79.99",
    image: courseProduction,
    category: "Producción",
    duration: "8 semanas",
    rating: 4.8,
  },
  {
    title: "Guitarra Avanzada: Técnicas de Fingerpicking",
    instructor: "Carlos Ramírez",
    price: "$54.99",
    image: courseGuitar,
    category: "Guitarra",
    duration: "9 semanas",
    rating: 4.9,
  },
  {
    title: "Introducción al Violín",
    instructor: "Elena Martín",
    price: "$44.99",
    image: coursePiano,
    category: "Violín",
    duration: "8 semanas",
    rating: 4.7,
  },
  {
    title: "Armonía y Composición",
    instructor: "Pedro Sánchez",
    price: "$49.99",
    image: coursePiano,
    category: "Teoría Musical",
    duration: "10 semanas",
    rating: 4.8,
  },
];
